apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec: # this part is just saying kubernetes has to find a storage instance with this access mode and  2Gi space
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 1Gi 

# volume claim not actual instance of storage: we just attache it to pod config
