apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  tls: # specify host for which we want to aquire certs
    - hosts: 
        - robertocampos.site
        - www.robertocampos.site
      secretName: k8-multi-com #  secret will contain the TLS private key and issued certificat
  rules: 
    - host: robertocampos.site
      http:
        paths: # there are two paths
          - path: /?(.*)
            backend: 
              serviceName: client-cluster-ip-service # points to 
              servicePort: 3000
          - path: /api/?(.*)
            backend: 
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.robertocampos.site
      http:
        paths: # there are two paths
          - path: /?(.*)
            backend: 
               serviceName: client-cluster-ip-service # points to 
               servicePort: 3000
          - path: /api/?(.*)
            backend: 
               serviceName: server-cluster-ip-service
               servicePort: 5000