apiVersion: cert-manager.k8.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory # acme is an issuer type
    email: 'campos.roberto100@gmail.com'
    privateKeySecretRef: 
      name: k8-multi-com
    solvers:
      - http01:
          ingress:
            class: nginx